"""creacion de las tablas roles, permisos y su n-n

Revision ID: 0fda96a1f8de
Revises:
Create Date: 2026-03-30 11:51:12.123725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0fda96a1f8de"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "permission_code",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "functionality",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("permission_code"),
        sa.CheckConstraint(
            "type IN ('endpoint', 'front', 'navigation')",
            name="check_type_constraint",
        ),
    )

    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "role_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permissions_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permissions_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id", "role_id", "permissions_id"),
    )
    # ### end Alembic commands ###
    #
    op.execute(
        "CREATE INDEX idx_permissions_type_active ON permissions (type, is_active);"
    )
    op.execute(
        "CREATE INDEX idx_permissions_functionality ON permissions (functionality);"
    )

    # ------------------------------ INSERTS ROLES PERMISOS --------------------------------
    # Roles
    op.execute(
        "INSERT INTO roles (id, name, profile_id, is_active, created_at, updated_at, created_by, updated_by) VALUES \
        ('82c846af-6537-441d-bdf1-bf6b652bfb35', 'Administrador', '80620ca1-0ffe-462f-9b27-2a98537aa642', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'); \
    "
    )

    # Permisos
    op.execute(
        "INSERT INTO permissions (id, permission_code, functionality, descripcion, type, is_active, created_at, updated_at, created_by, updated_by) VALUES \
        ('ff70eb8f-7708-4d43-9fce-519c2fa337b2', 'permissions:create-new-permissions', 'Permisos', 'Crear un nuevo permiso', 'endpoint', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('c59afa77-86de-40df-a0b8-529b0e0f16cc', 'permissions:get-all-permissions', 'Permisos', 'Listar todos los permisos del sistema', 'endpoint', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('00553d9a-da48-47bd-ae58-3a93f573d78c', 'permissions:update-permissions', 'Permisos', 'Actualizar un permiso', 'endpoint', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('63261891-4726-4f6f-b056-bce98930525a', 'permissions:deactivate-activate-permissions', 'Permisos', 'Activar o Desactivar un permiso', 'endpoint', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('992c6e79-e8a9-4494-b597-447356c57de5', 'roles:create-new-rol', 'Roles', 'Crear un nuevo rol', 'endpoint', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('1f52bb70-bd44-4663-9302-292755c0b9bf', 'roles:get-all-roles', 'Roles', 'Listar todos los roles del sistema', 'endpoint', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('f73bbaa3-25d0-4ff3-86f1-8e790b6613e1', 'roles:update-rol', 'Roles', 'Actualizar un rol', 'endpoint', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('84696fb9-407c-48c7-a66a-fcaa001d436b', 'roles:deactivate-activate-rol', 'Roles', 'Activar o Desactivar un rol', 'endpoint', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2','67033bd3-1ad0-40d7-80d6-9396c1aa38b2'); \
    "
    )

    # Roles-Permisos
    op.execute(
        "INSERT INTO role_permissions (id, role_id, permissions_id, is_active, created_at, updated_at, created_by, updated_by) VALUES \
        ('dcb9ad3e-5b29-4dae-b974-f3281c6d6ade', '82c846af-6537-441d-bdf1-bf6b652bfb35', 'ff70eb8f-7708-4d43-9fce-519c2fa337b2', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2', '67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('5b1fe49b-0952-4793-8a52-0a7051e5a8c6', '82c846af-6537-441d-bdf1-bf6b652bfb35', 'c59afa77-86de-40df-a0b8-529b0e0f16cc', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2', '67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('1f9012cb-43d2-4846-851f-d6661da01b7c', '82c846af-6537-441d-bdf1-bf6b652bfb35', '00553d9a-da48-47bd-ae58-3a93f573d78c', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2', '67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('fb45fe59-4508-4aa2-8833-3209b9a9df33', '82c846af-6537-441d-bdf1-bf6b652bfb35', '63261891-4726-4f6f-b056-bce98930525a', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2', '67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('cdd8e5ef-cd16-412b-a6ea-2831e4bdba39', '82c846af-6537-441d-bdf1-bf6b652bfb35', '992c6e79-e8a9-4494-b597-447356c57de5', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2', '67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('2b5a7904-7603-4632-93fd-2cfd32665bc7', '82c846af-6537-441d-bdf1-bf6b652bfb35', '1f52bb70-bd44-4663-9302-292755c0b9bf', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2', '67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('e730af88-727c-4ea4-829a-2e583ecdebf8', '82c846af-6537-441d-bdf1-bf6b652bfb35', 'f73bbaa3-25d0-4ff3-86f1-8e790b6613e1', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2', '67033bd3-1ad0-40d7-80d6-9396c1aa38b2'), \
        ('11aa86e0-6970-47c6-9b5d-904c1f3b43e8', '82c846af-6537-441d-bdf1-bf6b652bfb35', '84696fb9-407c-48c7-a66a-fcaa001d436b', true, NOW(), NOW(), '67033bd3-1ad0-40d7-80d6-9396c1aa38b2', '67033bd3-1ad0-40d7-80d6-9396c1aa38b2'); \
    "
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
