"""Creacion tabla de books

Revision ID: 28693bb42724
Revises:
Create Date: 2026-03-31 13:51:41.593404

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28693bb42724"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "author", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("isbn", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "selling_price_local", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "category", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "supplier_country",
            sqlmodel.sql.sqltypes.AutoString(length=5),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isbn"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    # ### end Alembic commands ###
